#!/bin/sh
# https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-repository
# runs=https://api.github.com/repos/e2dk4r/handmadehero/actions/runs?per_page=1

workflow=${1:-compile.yml}
if [ ! -e .github/workflows/${workflow} ]; then
  echo workflow is invalid
  echo workflows:
  for workflow in .github/workflows/*; do
     workflow=${workflow##.github/workflows/}
     echo "  $workflow"
  done
  exit 1
fi

# https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-workflow
runs=https://api.github.com/repos/e2dk4r/handmadehero/actions/workflows/${workflow}/runs?per_page=1
props=$(cat <<END
id
name
head_branch
head_sha
display_title
run_number
html_url
status
conclusion
END
)
jq_filter=".workflow_runs[0] | $(echo $props | sed 's/ /,./g' | sed 's/^/./')"

curl -s "$runs" | jq "$jq_filter"

