#ifndef HANDMADEHERO_ERROR_H
#define HANDMADEHERO_ERROR_H

#define HANDMADEHERO_ERROR_IO_URING_SETUP 10
#define HANDMADEHERO_ERROR_IO_URING_WAIT 11
#define HANDMADEHERO_ERROR_UDEV_SETUP 20
#define HANDMADEHERO_ERROR_UDEV_MONITOR 21
#define HANDMADEHERO_ERROR_UDEV_POLL 22
#define HANDMADEHERO_ERROR_WAYLAND_CONNECT 30
#define HANDMADEHERO_ERROR_WAYLAND_REGISTRY 31
#define HANDMADEHERO_ERROR_WAYLAND_EXTENSIONS 33
#define HANDMADEHERO_ERROR_WAYLAND_FD 34
#define HANDMADEHERO_ERROR_WAYLAND_SHM_POOL 34
#define HANDMADEHERO_ERROR_XKB 40
#define HANDMADEHERO_ERROR_ALLOCATION 50
#define HANDMADEHERO_ERROR_SHARED_MEMORY 60

#endif /* HANDMADEHERO_ERROR_H */
