#ifndef HANDMADEHERO_ERROR_H
#define HANDMADEHERO_ERROR_H

#define HANDMADEHERO_ERROR_IO_URING_SETUP 10
#define HANDMADEHERO_ERROR_IO_URING_WAIT 11

#define HANDMADEHERO_ERROR_INOTIFY_SETUP 20
#define HANDMADEHERO_ERROR_INOTIFY_WATCH_SETUP 21
#define HANDMADEHERO_ERROR_INOTIFY_WATCH 21
#define HANDMADEHERO_ERROR_INOTIFY_WATCH_POLL 22

#define HANDMADEHERO_ERROR_DEV_INPUT_DIR_OPEN 70
#define HANDMADEHERO_ERROR_DEV_INPUT_DIR_READ 71

#define HANDMADEHERO_ERROR_WAYLAND_CONNECT 30
#define HANDMADEHERO_ERROR_WAYLAND_REGISTRY 31
#define HANDMADEHERO_ERROR_WAYLAND_EXTENSIONS 33
#define HANDMADEHERO_ERROR_WAYLAND_FD 34
#define HANDMADEHERO_ERROR_WAYLAND_SHM_POOL 34

#define HANDMADEHERO_ERROR_XKB 40

#define HANDMADEHERO_ERROR_ALLOCATION 50
#define HANDMADEHERO_ERROR_SHARED_MEMORY 60

#define HANDMADEHERO_ERROR_THREAD_INIT 80

#define HANDMADEHERO_ERROR_PIPEWIRE 90

enum handmadehero_error {
  HANDMADEHERO_ERROR_NONE = 0,
  HANDMADEHERO_ERROR_OPEN_FILE,
  HANDMADEHERO_ERROR_PATH_IS_NOT_FILE,
  HANDMADEHERO_ERROR_READ_FROM_FILE,
  HANDMADEHERO_ERROR_FILE_STAT,
  HANDMADEHERO_ERROR_FILE_SEEK,

  HANDMADEHERO_ERROR_FILE_IS_NOT_HHA,
  HANDMADEHERO_ERROR_HHA_VERSION_IS_NOT_SUPPORTED,
};

#endif /* HANDMADEHERO_ERROR_H */
