name: compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  NINJA_VERSION: '1.12.1'
  MUON_VERSION: '0.2.0'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PKG_CONFIG_PATH: '/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig'
    steps:
    - uses: actions/checkout@v3

    - name: install packages
      run: sudo apt-get install -y --no-install-recommends --no-install-suggests
           wget unzip libarchive-tools
           nasm
           pkg-config
           libevdev-dev liburing-dev
           libwayland-dev libwayland-client0 wayland-protocols libxkbcommon-dev
           libpipewire-0.3-dev;

           sudo ln -sf /usr/bin/bsdtar /usr/bin/tar;

           wget https://github.com/ninja-build/ninja/releases/download/v$NINJA_VERSION/ninja-linux.zip;
           unzip ninja-linux.zip; rm ninja-linux.zip;
           sudo mv ninja /usr/bin/;

           wget https://muon.build/releases/v$MUON_VERSION/muon-$MUON_VERSION-amd64-linux-static;
           chmod 755 muon-$MUON_VERSION-amd64-linux-static;
           sudo mv muon-$MUON_VERSION-amd64-linux-static /usr/bin/meson;

    - name: configure
      run: meson setup build -Ddefault_library=shared

    - name: ninja
      run: ninja -C build

    - name: release
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ startsWith(github.event.head_commit.message, 'watchlist:') }}
      continue-on-error: true
      run: |
        day=$(echo ${{ github.event.head_commit.message }} | tr ' ' '\n' | tail -n 1)
        output=handmadehero-day-$day
        file=$output.tar.zst

        mkdir $output
        cp script/extract_art build/handmadehero build/libhandmadehero.so $output
        tar cf - $output | zstd --ultra -22 -T0 -o $file

        echo **Workflow run**: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID >> notes

        echo '' >> notes
        echo '> [!IMPORTANT]' >> notes
        echo '> **DO NOT FORGET** to extract art archive' >> notes

        echo '' >> notes
        echo '# Keyboard Input' >> notes
        echo '| key   | meaning           |' >> notes
        echo '|-------|-------------------|' >> notes
        echo '| q     | Exit the game     |' >> notes
        echo '| l     | Loop mode toggle  |' >> notes
        echo '| f     | Go to fullscreen  |' >> notes
        echo '| space | Create player     |' >> notes
        echo '| w     | Go to up          |' >> notes
        echo '| a     | Go to left        |' >> notes
        echo '| s     | Go to down        |' >> notes
        echo '| d     | Go to right       |' >> notes
        echo '| space | Jump              |' >> notes

        echo '' >> notes
        echo '# Gamepad Input' >> notes
        echo '| key        | meaning                     |' >> notes
        echo '|------------|-----------------------------|' >> notes
        echo '| start      | Create player               |' >> notes
        echo '| dpad       | Go to up, left, down, right |' >> notes
        echo '| left stick | Go to up, left, down, right |' >> notes
        echo '| start      | Jump                        |' >> notes

        gh release create day-$day --notes-file notes $file
