name: compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install packages
      run: sudo apt-get install -y --no-install-recommends --no-install-suggests
           wget python3 unzip libarchive-tools
           nasm
           pkg-config
           libevdev-dev liburing-dev
           libvulkan-dev libwayland-dev libwayland-client0 wayland-protocols libxkbcommon-dev;

           sudo ln -sf /usr/bin/bsdtar /usr/bin/tar;

           NINJA_VERSION=1.12.1;
           wget https://github.com/ninja-build/ninja/releases/download/v$NINJA_VERSION/ninja-linux.zip;
           unzip ninja-linux.zip; rm ninja-linux.zip;
           sudo mv ninja /usr/bin/;

           MESON_VERSION=1.4.0;
           wget https://github.com/mesonbuild/meson/releases/download/$MESON_VERSION/meson-$MESON_VERSION.tar.gz;
           tar xf meson-$MESON_VERSION.tar.gz; rm meson-$MESON_VERSION.tar.gz;
           sudo mv meson-$MESON_VERSION/mesonbuild /usr/lib/python3/dist-packages/; sudo mv meson-$MESON_VERSION/meson.py /usr/bin/meson;
           rm -rf meson-$MESON_VERSION/;

    - name: configure
      run: meson setup build

    - name: ninja
      run: ninja -C build

    - name: release
      env:
        GH_TOKEN: ${{ github.token }}
      if: ${{ startsWith(github.event.head_commit.message, 'watchlist:') }}
      continue-on-error: true
      run: |
        day=$(echo ${{ github.event.head_commit.message }} | tr ' ' '\n' | tail -n 1)
        output=handmadehero-day-$day
        file=$output.tar.zst

        mkdir $output
        cp script/extract_art build/handmadehero build/libhandmadehero.so $output
        tar cf - $output | zstd --ultra -22 -T0 -o $file

        echo **Workflow run**: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID >> notes

        echo '' >> notes
        echo '> [!IMPORTANT]' >> notes
        echo '> **DO NOT FORGET** to extract art archive' >> notes

        echo '' >> notes
        echo '# Keyboard Input' >> notes
        echo '| key   | meaning           |' >> notes
        echo '|-------|-------------------|' >> notes
        echo '| q     | Exit the game     |' >> notes
        echo '| l     | Loop mode toggle  |' >> notes
        echo '| f     | Go to fullscreen  |' >> notes
        echo '| space | Create player     |' >> notes
        echo '| w     | Go to up          |' >> notes
        echo '| a     | Go to left        |' >> notes
        echo '| s     | Go to down        |' >> notes
        echo '| d     | Go to right       |' >> notes
        echo '| space | Jump              |' >> notes

        echo '' >> notes
        echo '# Gamepad Input' >> notes
        echo '| key        | meaning                     |' >> notes
        echo '|------------|-----------------------------|' >> notes
        echo '| start      | Create player               |' >> notes
        echo '| dpad       | Go to up, left, down, right |' >> notes
        echo '| left stick | Go to up, left, down, right |' >> notes
        echo '| start      | Jump                        |' >> notes

        gh release create day-$day --notes-file notes $file
