name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CC: gcc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install packages
      run: sudo apt-get install -y --no-install-recommends --no-install-suggests
           libevdev-dev liburing-dev
           libwayland-dev libwayland-client0 wayland-protocols libxkbcommon-dev
           libpipewire-0.3-dev;

    - name: configure
      run: sed -i 's/IsBuildEnabled=1/IsBuildEnabled=0/' build.sh

    - name: test
      run: CC=gcc ./build.sh
