name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  NINJA_VERSION: '1.12.1'
  MESON_VERSION: '1.5.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install packages
      run: sudo apt-get install -y --no-install-recommends --no-install-suggests
           wget unzip libarchive-tools
           nasm
           pkg-config
           libevdev-dev liburing-dev
           libwayland-dev libwayland-client0 wayland-protocols libxkbcommon-dev
           libpipewire-0.3-dev;

           sudo ln -sf /usr/bin/bsdtar /usr/bin/tar;

           wget https://github.com/ninja-build/ninja/releases/download/v$NINJA_VERSION/ninja-linux.zip;
           unzip ninja-linux.zip; rm ninja-linux.zip;
           sudo mv ninja /usr/bin/;

           wget https://github.com/mesonbuild/meson/releases/download/$MESON_VERSION/meson-$MESON_VERSION.tar.gz;
           tar xf meson-$MESON_VERSION.tar.gz; rm meson-$MESON_VERSION.tar.gz;
           sudo mv meson-$MESON_VERSION/mesonbuild /usr/lib/python3/dist-packages/; sudo mv meson-$MESON_VERSION/meson.py /usr/bin/meson;
           rm -rf meson-$MESON_VERSION/;

    - name: configure
      run: meson setup build

    - name: test
      run: meson test -C build
